"""empty message

Revision ID: 2c9a6083e499
Revises: e63479d786a3
Create Date: 2018-09-05 18:15:06.538425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9a6083e499'
down_revision = 'e63479d786a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Articles', sa.Column('image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Articles', 'image')
    # ### end Alembic commands ###
