"""empty message

Revision ID: 81281bca10b9
Revises: 
Create Date: 2018-09-01 16:02:36.599802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81281bca10b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Articles')
    # ### end Alembic commands ###
